### PR TITLE
Improve install instructions

### PR DESCRIPTION
**Pull request by bersling**
Change from `npm install --save svelte-confetti` to `npm install --save-dev svelte-confetti`

### CODE REVIEW

**Comment by Mitcheljager** [comment]
Could you explain why? I understand that theoretically everything in `Svelte` is a devDependency since it's all compiled, but I think the distinction still makes sense.

**Comment by LeoDog896** [comment]
> Could you explain why? I understand that theoretically everything in `Svelte` is a devDependency since it's all compiled, but I think the distinction still makes sense.

Dev dependencies are used for sites - e.g. if you're making a Svelte Library, generally, `svelte-confetti` would be used as a display for the Demo site, not the library itself. In the case of a normal Svelte / SvelteKit site, dev dependencies are preferred (simply as a style reason), and are [generally standard](https://mdsvex.com/docs) across different libraries.

**Comment by xpat** [comment]
I second this pull request.  After running `npm install --save svelte-confetti` as indicated in the instructions, I got that error and my Cloudflare deployment failed but not the case after running `npm install -D svelte-confetti`. [ Advice I followed on Discord](https://discord.com/channels/457912077277855764/1133191687880065065/1133198754078535781) to avoid this error is to install as a devDependency and that worked.  It's the only thing I changed and I went from failed deployment to successful.

**Comment by Mitcheljager** [comment]
Fair enough, I'll merge it in!

**Pull request merged**
